'use client';

import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';
import { GraduationCap, ArrowRight, Sparkles, CalendarClock, MessageSquare, Brain } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { APP_NAME } from '@/constants';

export default function HomePage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-background gradient-mesh flex flex-col">
      {/* Hero */}
      <div className="flex-1 flex flex-col items-center justify-center px-4 py-20 text-center">
        {/* Badge */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="mb-6"
        >
          <span className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-xs font-medium text-primary">
            <Sparkles className="h-3 w-3" />
            AI-Powered Student Productivity
          </span>
        </motion.div>

        {/* Logo */}
        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mb-6 flex h-20 w-20 items-center justify-center rounded-3xl gradient-primary shadow-lg shadow-primary/25 glow"
        >
          <GraduationCap className="h-10 w-10 text-white" />
        </motion.div>

        {/* Title */}
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="text-4xl md:text-6xl font-bold tracking-tight mb-4"
        >
          <span className="bg-gradient-to-r from-primary via-purple-500 to-blue-500 bg-clip-text text-transparent">
            {APP_NAME}
          </span>
        </motion.h1>

        {/* Subtitle */}
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
          className="text-lg md:text-xl text-muted-foreground max-w-2xl mb-8 leading-relaxed"
        >
          Smart deadlines. AI study plans. WhatsApp reminders. Google Calendar sync.
          <br />
          <span className="text-foreground font-medium">
            Everything a student needs to stay ahead.
          </span>
        </motion.p>

        {/* CTA Buttons */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="flex flex-col sm:flex-row gap-3"
        >
          <Button
            size="lg"
            variant="gradient"
            className="text-base px-8"
            onClick={() => router.push('/onboarding')}
          >
            Get Started
            <ArrowRight className="h-4 w-4" />
          </Button>
          <Button
            size="lg"
            variant="outline"
            className="text-base px-8"
            onClick={() => router.push('/dashboard')}
          >
            View Dashboard
          </Button>
        </motion.div>

        {/* Feature Cards */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.6 }}
          className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-16 w-full max-w-3xl"
        >
          {[
            {
              icon: CalendarClock,
              title: 'Smart Deadlines',
              desc: 'Never miss an assignment with intelligent reminders',
            },
            {
              icon: Brain,
              title: 'AI Study Plans',
              desc: 'Personalized study schedules generated by AI',
            },
            {
              icon: MessageSquare,
              title: 'WhatsApp Alerts',
              desc: 'Automated reminders straight to your phone',
            },
          ].map((feature, idx) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.7 + idx * 0.1 }}
              className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-sm p-5 text-left hover:border-primary/30 hover:shadow-lg hover:shadow-primary/5 transition-all duration-300"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 mb-3">
                <feature.icon className="h-5 w-5 text-primary" />
              </div>
              <h3 className="text-sm font-semibold mb-1">{feature.title}</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                {feature.desc}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </div>

      {/* Footer */}
      <footer className="border-t border-border/50 py-4 px-4 text-center">
        <p className="text-xs text-muted-foreground">
          Built with ❤️ for{' '}
          <span className="font-medium text-foreground">CodeStorm Hackathon 2025</span>
        </p>
      </footer>
    </div>
  );
}
