// ============================================================
// CampusFlow — API Service Layer (Placeholder)
// Backend team replaces mock data with real API calls
// ============================================================

import axios from 'axios';
import { API_BASE_URL } from '@/constants';
import type {
  Student,
  StudentOnboardingData,
  Deadline,
  CreateDeadlineData,
  StudyPlan,
  Automation,
  DashboardStats,
  Notification,
  ApiResponse,
} from '@/types';
import {
  mockStudent,
  mockDeadlines,
  mockStudyPlan,
  mockAutomations,
  mockStats,
  mockNotifications,
} from '@/lib/mock-data';

// ---- Axios Instance ----
const api = axios.create({
  baseURL: API_BASE_URL,
  headers: { 'Content-Type': 'application/json' },
  timeout: 10000,
});

// ---- Helper: Simulate API delay ----
const delay = (ms: number = 500) => new Promise((resolve) => setTimeout(resolve, ms));

// ============================================================
// Student Service
// ============================================================
export const studentService = {
  async onboard(data: StudentOnboardingData): Promise<ApiResponse<Student>> {
    await delay(800);
    // TODO: Replace with — api.post('/students/onboard', data)
    return {
      data: { ...mockStudent, ...data, id: 'stu-new', year: parseInt(data.year) },
      success: true,
      message: 'Onboarding successful',
    };
  },

  async getProfile(): Promise<ApiResponse<Student>> {
    await delay();
    // TODO: Replace with — api.get('/students/profile')
    return { data: mockStudent, success: true, message: 'Profile fetched' };
  },
};

// ============================================================
// Deadline Service
// ============================================================
export const deadlineService = {
  async getAll(): Promise<ApiResponse<Deadline[]>> {
    await delay();
    // TODO: Replace with — api.get('/deadlines')
    return { data: mockDeadlines, success: true, message: 'Deadlines fetched' };
  },

  async getById(id: string): Promise<ApiResponse<Deadline>> {
    await delay();
    // TODO: Replace with — api.get(`/deadlines/${id}`)
    const deadline = mockDeadlines.find((d) => d.id === id);
    return {
      data: deadline || mockDeadlines[0],
      success: !!deadline,
      message: deadline ? 'Deadline fetched' : 'Not found',
    };
  },

  async create(data: CreateDeadlineData): Promise<ApiResponse<Deadline>> {
    await delay(800);
    // TODO: Replace with — api.post('/deadlines', data)
    const newDeadline: Deadline = {
      ...data,
      id: `dl-${Date.now()}`,
      status: 'pending',
      automationStatus: 'waiting',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    return { data: newDeadline, success: true, message: 'Deadline created' };
  },

  async update(id: string, data: Partial<CreateDeadlineData>): Promise<ApiResponse<Deadline>> {
    await delay(600);
    // TODO: Replace with — api.put(`/deadlines/${id}`, data)
    const existing = mockDeadlines.find((d) => d.id === id) || mockDeadlines[0];
    return {
      data: { ...existing, ...data, updatedAt: new Date().toISOString() },
      success: true,
      message: 'Deadline updated',
    };
  },

  async delete(id: string): Promise<ApiResponse<null>> {
    await delay(400);
    // TODO: Replace with — api.delete(`/deadlines/${id}`)
    void id;
    return { data: null, success: true, message: 'Deadline deleted' };
  },
};

// ============================================================
// Study Plan Service
// ============================================================
export const studyPlanService = {
  async generate(deadlineId: string): Promise<ApiResponse<StudyPlan>> {
    await delay(2000); // Simulate AI generation time
    // TODO: Replace with — api.post('/study-plans/generate', { deadlineId })
    return {
      data: { ...mockStudyPlan, deadlineId },
      success: true,
      message: 'Study plan generated by AI',
    };
  },
};

// ============================================================
// Automation Service
// ============================================================
export const automationService = {
  async getAll(): Promise<ApiResponse<Automation[]>> {
    await delay();
    // TODO: Replace with — api.get('/automations')
    return { data: mockAutomations, success: true, message: 'Automations fetched' };
  },

  async trigger(automationId: string): Promise<ApiResponse<Automation>> {
    await delay(1000);
    // TODO: Replace with — api.post(`/automations/${automationId}/trigger`)
    const automation = mockAutomations.find((a) => a.id === automationId) || mockAutomations[0];
    return {
      data: { ...automation, status: 'running' },
      success: true,
      message: 'Automation triggered',
    };
  },
};

// ============================================================
// Dashboard Service
// ============================================================
export const dashboardService = {
  async getStats(): Promise<ApiResponse<DashboardStats>> {
    await delay();
    // TODO: Replace with — api.get('/dashboard/stats')
    return { data: mockStats, success: true, message: 'Stats fetched' };
  },

  async getNotifications(): Promise<ApiResponse<Notification[]>> {
    await delay();
    // TODO: Replace with — api.get('/notifications')
    return { data: mockNotifications, success: true, message: 'Notifications fetched' };
  },

  async markNotificationRead(id: string): Promise<ApiResponse<null>> {
    await delay(200);
    // TODO: Replace with — api.patch(`/notifications/${id}`, { read: true })
    void id;
    return { data: null, success: true, message: 'Notification marked as read' };
  },
};

export default api;
